#! /usr/bin/bash

# Dont know why this command just works like this.

 docker build \
 --build-arg REACT_APP_BACKEND_URL="https://api.myappcruddur.com" \
 --build-arg REACT_APP_AWS_PROJECT_REGION="eu-central-1" \
 --build-arg REACT_APP_AWS_COGNITO_REGION="eu-central-1" \
 --build-arg REACT_APP_AWS_USER_POOLS_ID="eu-central-1_m6hu1cbSu" \
 --build-arg REACT_APP_CLIENT_ID="6h42orvqfbgku4g88q0lnjou1u" \
 -t frontend-react-js \
 -f "Dockerfile.prod" \
 "."
