#! /usr/bin/bash

 docker build \
 --build-arg REACT_APP_BACKEND_URL="http://cruder-alb-1341597399.eu-central-1.elb.amazonaws.com:4567" \
 --build-arg REACT_APP_AWS_PROJECT_REGION="$AWS_DEFAULT_REGION" \
 --build-arg REACT_APP_AWS_COGNITO_REGION="$AWS_DEFAULT_REGION" \
 --build-arg REACT_APP_AWS_USER_POOLS_ID="$AWS_USER_POOLS_ID" \
 --build-arg REACT_APP_CLIENT_ID="$APP_CLIENT_ID" \
 -t frontend-react-js \
 -f "Dockerfile.prod" \
 "."

 